#!/usr/bin/env python3
"""Generate the checked-in quarter-wave signed Q15 sine table (RH1A).

Writes `hil/source/core/hil_source_sine_lut.inc` with 257 entries:

    lut[i] = round(sin(pi*i/512) * 32767)   for i in [0, 256]

The C signal module mirrors these 257 quarter-wave entries into the full
1024 phase indices at runtime (see hil_source_signal.c).  The generator
has mutually exclusive `--write` and `--check` modes and defaults to no
destructive rewrite: a bare invocation behaves like `--check` and never
modifies the file.

Exit status: 0 clean, 1 drift/missing file or I/O error, 2 usage error
(such as passing both `--write` and `--check`).
"""

import argparse
import math
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
OUT_PATH = os.path.join(REPO_ROOT, "hil", "source", "core", "hil_source_sine_lut.inc")

ENTRIES = 257  # i in [0, 256]
PER_LINE = 16


def table_entries():
    return [int(round(math.sin(math.pi * i / 512.0) * 32767.0)) for i in range(ENTRIES)]


def render(entries):
    lines = [
        "/* Generated by scripts/generate_hil_source_sine_lut.py. Do not edit by hand.",
        " * 257-entry quarter-wave signed Q15 sine table, i in [0, 256]:",
        " *   lut[i] = round(sin(pi*i/512) * 32767)",
        " * Mirrored at runtime into 1024 phase indices (see hil_source_signal.c).",
        " */",
        "static const int16_t hil_source_sine_lut[257] = {",
    ]
    for i in range(0, ENTRIES, PER_LINE):
        chunk = entries[i : i + PER_LINE]
        lines.append("\t" + ", ".join("%4d" % v for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="generate hil/source/core/hil_source_sine_lut.inc"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--write", action="store_true", help="rewrite the checked-in table"
    )
    group.add_argument(
        "--check", action="store_true", help="verify the checked-in table (default)"
    )
    args = parser.parse_args(argv)

    expected = render(table_entries())

    if args.write:
        try:
            with open(OUT_PATH, "w", encoding="utf-8") as fh:
                fh.write(expected)
        except OSError as exc:
            print(
                "generate_hil_source_sine_lut: cannot write %s: %s" % (OUT_PATH, exc),
                file=sys.stderr,
            )
            return 1
        print("wrote %s" % OUT_PATH)
        return 0

    try:
        with open(OUT_PATH, "r", encoding="utf-8") as fh:
            current = fh.read()
    except OSError as exc:
        print(
            "generate_hil_source_sine_lut: cannot read %s: %s" % (OUT_PATH, exc),
            file=sys.stderr,
        )
        return 1

    if current != expected:
        print("generate_hil_source_sine_lut: DRIFT in %s" % OUT_PATH, file=sys.stderr)
        return 1
    print("generate_hil_source_sine_lut: %s is clean" % OUT_PATH)
    return 0


if __name__ == "__main__":
    sys.exit(main())
